# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  leader-election:
    type: boolean
    default: false
    description: Enable leader election
  tensorboard-image:
    type: string
    default: "docker.io/charmedkubeflow/tensorflow:2.5.1-2836bb9"
    description: Tensorboard image used for visualizations
