# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  backend-mode:
    type: string
    default: production
    description: Which mode out of `development` or `production` the backend server should use
  secure-cookies:
    type: boolean
    default: false
    description: Whether cookies should require HTTPS
