name: On Push

# On push to a "special" branch, we:
# * always publish to charmhub at latest/edge/branchname
# * always run tests
# where a "special" branch is one of main or track/**, as
# by convention these branches are the source for a corresponding
# charmhub edge channel.

on:
  push:
    branches:
    - main
    - track/**

jobs:
  get-charm-paths:
    name: Generate the Charm Matrix content
    runs-on: ubuntu-latest
    outputs:
      charm-paths: ${{ steps.get-charm-paths.outputs.charm-paths }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get paths for all charms in this repo
        id: get-charm-paths
        uses: canonical/kubeflow-ci/actions/get-charm-paths@main

  build:
    strategy:
      matrix:
        charm: ${{ fromJSON(needs.get-charm-paths.outputs.charm-paths) }}
    name: Build charm | ${{ matrix.charm }}
    needs:
      - get-charm-paths
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v29.0.0
    with:
      charmcraft-snap-channel: latest/candidate  # TODO: remove after charmcraft 3.3 stable release
      path-to-charm-directory: ${{ matrix.charm }}

  tests:
    name: Run Tests
    needs: build
    uses: ./.github/workflows/integrate.yaml
    secrets: inherit

  # publish runs in series with tests, and only publishes if tests passes
  publish-charm:
    name: Publish Charm
    needs: tests
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
